name: ecommerce
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  lottie: ^1.2.1
  font_awesome_flutter: ^9.2.0
  provider: ^6.0.2
  firebase_auth: ^3.3.6
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^4.0.1
  flutter_pagewise: ^2.0.1

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/products/
    - assets/fonts/
# fonts:
#   - family: FreeZone
#     fonts:
#       - asset: assets/fonts/FreeZone-Medium.ttf
#       - asset: assets/fonts/FreeZone-Regular.ttf